name: qr_code_scanner
description: A cross-platform QR code scanner Flutter application for all platforms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  intl: ^0.20.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  google_mobile_ads: ^5.0.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  flutter_contacts: ^1.1.7
  path_provider: ^2.1.4
  appsflyer_sdk: ^6.6.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/

